# Generated by Django 3.2.12 on 2024-08-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20240830_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapeddata',
            old_name='property_categories',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='scrapeddata',
            old_name='property_images',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='scrapeddata',
            old_name='property_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='scrapeddata',
            old_name='url',
            new_name='urls',
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='emails',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
